In [1]:
import pandas as pd
import numpy as np

pandas es excel para python y numpy es matlab para python

In [2]:
dataf = pd.read_csv("full_data.csv", header=1, decimal=",", sep=";")

In [3]:
dataf

Base X    Base Y    Base Z  Extremo X  Extremo Y  Extremo Z    1    2  \
0     0.000219 -0.000119  0.000062  -0.030063  -0.024100   0.245865  800 -800   
1    -0.000088 -0.000003 -0.000015   0.002091  -0.001694   0.244900  800 -800   
2     0.000186 -0.000118  0.000038  -0.023397  -0.004430   0.243800  800 -800   
3     0.000196 -0.000110  0.000074  -0.012293  -0.019218   0.245357  800 -800   
4     0.000195 -0.000102  0.000056  -0.029423  -0.022540   0.244960  800 -800   
...        ...       ...       ...        ...        ...        ...  ...  ...   
5070  0.000002 -0.000001 -0.000037   0.007510   0.001981   0.247224 -500  500   
5071 -0.000138  0.000210  0.000225  -0.010857   0.007735   0.247674 -500  500   
5072  0.000060 -0.000012 -0.000061   0.001390   0.002158   0.247438 -500  500   
5073  0.000139 -0.000045 -0.000123  -0.004166   0.007253   0.247639 -500  500   
5074  0.000007  0.000003 -0.000018   0.009505   0.000381   0.247286 -500  500   

        3    4  ...  7  8    9   10    11    12   13   14   15   16  
0       0    0  ...  0  0  800 -800     0     0  800 -800    0    0  
1       0    0  ...  0  0  800 -800     0     0 -800  800    0    0  
2       0    0  ...  0  0  800 -800     0     0    0    0  800 -800  
3       0    0  ...  0  0  800 -800     0     0    0    0 -800  800  
4       0    0  ...  0  0 -800  800     0     0  800 -800    0    0  
...   ...  ...  ... .. ..  ...  ...   ...   ...  ...  ...  ...  ...  
5070  500 -500  ...  0  0 -500  500 -1200  1200    0    0    0    0  
5071 -500  500  ...  0  0  500 -500  1200 -1200    0    0    0    0  
5072 -500  500  ...  0  0  500 -500 -1200  1200    0    0    0    0  
5073 -500  500  ...  0  0 -500  500  1200 -1200    0    0    0    0  
5074 -500  500  ...  0  0 -500  500 -1200  1200    0    0    0    0  

[5075 rows x 22 columns]

In [4]:
dataf = dataf.iloc[:1399] # Me quedo con los 1400 primeros puntos
# Shuffle the data
dataf = dataf.sample(frac=1).reset_index(drop=True)
dataf

Base X    Base Y    Base Z  Extremo X  Extremo Y  Extremo Z    1    2  \
0     0.000106 -0.000117  0.000017  -0.015168  -0.008616   0.245337  800 -800   
1    -0.000177 -0.000107  0.000191   0.009128   0.016756   0.254222 -500  500   
2    -0.000180 -0.000386  0.000328   0.020454   0.008539   0.252135    0    0   
3    -0.000145  0.000207  0.000538   0.022778   0.024052   0.252923 -500  500   
4     0.000102 -0.000032  0.000078  -0.005267  -0.009781   0.244621  800 -800   
...        ...       ...       ...        ...        ...        ...  ...  ...   
1394 -0.000017  0.000041 -0.000013   0.001706  -0.001329   0.249468  200 -200   
1395 -0.000218  0.000065  0.000762   0.029445   0.017359   0.250747    0    0   
1396  0.000054 -0.000106  0.000125   0.000384   0.009009   0.250470    0    0   
1397  0.000125 -0.000069 -0.000012  -0.004563  -0.002767   0.247827  500 -500   
1398 -0.000105 -0.000137  0.000100   0.021392   0.023613   0.251954    0    0   

        3    4  ...    7    8    9    10   11   12   13   14   15   16  
0     800 -800  ... -800  800  800  -800 -800  800  800 -800 -800  800  
1       0    0  ...    0    0 -500   500    0    0  500 -500    0    0  
2     500 -500  ...  500 -500    0     0 -500  500    0    0  500 -500  
3       0    0  ...  500 -500    0     0  500 -500  500 -500    0    0  
4       0    0  ...    0    0    0     0  800 -800 -800  800    0    0  
...   ...  ...  ...  ...  ...  ...   ...  ...  ...  ...  ...  ...  ...  
1394 -400  400  ...    0    0    0     0    0    0    0    0    0    0  
1395  500 -500  ...  500 -500  500  -500    0    0    0    0  500 -500  
1396    0    0  ...    0    0    0  1000    0    0    0    0    0    0  
1397  500 -500  ... -500  500  500  -500  500 -500 -500  500 -500  500  
1398  500 -500  ...  500 -500  500  -500    0    0  500 -500    0    0  

[1399 rows x 22 columns]

In [5]:
Y = dataf[["Extremo X", "Extremo Y"]].to_numpy()

In [6]:
Y

array([[-0.01516753, -0.00861558],
       [ 0.00912837,  0.01675559],
       [ 0.02045409,  0.00853943],
       ...,
       [ 0.00038356,  0.00900868],
       [-0.00456344, -0.00276677],
       [ 0.02139216,  0.02361276]])

In [7]:
X = dataf.to_numpy()[:, 6::2]

Nos quedamos con todas las filas y despreciamos las seis primeras columnas y luego cogemos las columnas restantes una sí una no, para quedarnos con los motores impares.
Y son las posiciones (x,y) y X son los motores impares

In [8]:
X.shape

(1399, 8)

In [9]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, make_scorer
from sklearn.model_selection import GridSearchCV

He distribuido los valores de X y de Y entre -1 y 1 haciendo una transformación lineal. Es solo porque los algoritmos se suelen llevar mejor con números pequeños y parecidos entre sí, nada más.
También me he cargado las posiciones Z, no sé si con buen o con mal criterio. Me ha parecido con un vistazo rápido que el robot se mueve en el plano (x,y).
También elijo entrenar solo los motores impares, los pares se pueden obtener a partir de ellos.

In [10]:
y_scaler = MinMaxScaler((-1,1)).fit(Y)
Y = y_scaler.transform(Y)

In [11]:
y_scaler.data_min_, y_scaler.data_max_

(array([-0.04992126, -0.03767348]), array([0.04602556, 0.051251  ]))

In [12]:
import joblib
joblib.dump(y_scaler, "yscaler.joblib")

['yscaler.joblib']

In [13]:
scaler = MinMaxScaler((-1,1))

In [14]:
regressor = MLPRegressor(
    verbose=False,
    random_state=42,
    activation = "relu",
    early_stopping = True,
    max_iter=1000,
)

random state es la semilla del generador de números aleatorios. Solo sirve para que cada vez que ejecutes el script te salga lo mismo. 
early stopping True significa tener un mini test set para parar de entrenar antes de hacer overfitting.
max_iter=600, significa que cada elemento del traning set se le ha enseñado a la red un máximo de 600 veces.
optimizador adam. Recordar citarlo en el TFM.

In [15]:
model = Pipeline(steps =[
    ("scaler", scaler),
    ("nn", regressor),
])

In [16]:
param_grid = {"nn__hidden_layer_sizes":[(50,50),(100,100), (150,150), (50,),(100,), (150,)],
             "nn__learning_rate_init": [0.0001,0.0005,0.001,0.005,0.01,0.05],
             "nn__alpha": [0.0001,0.0005,0.001,0.005,0.01,0.05],
            }

alpha es el peso de la regularizacion L2, si es pequeño permite overfitting y si es grande produce underfitting. Si es grande fuerza a que los parámetros (W1, W2, W3...) sean demasiado pequeños, si es 0 los parametros pueden ser arbitrariamente grandes.

In [17]:
cv_1layer = GridSearchCV(model, param_grid, scoring=make_scorer(r2_score), verbose=1, n_jobs=4, cv=5)

cv = 3 signifca que he hecho cross validation con tres particiones en vez de con 5, porque tardaba la vida. 
n_jobs=4 significa que he usado las 4 CPUs que tiene mi ordenador para entrenar
scoring=r2, significa que he elegido como mejor red la que tiene mejor coeficiente de correlacion entre los y_test y los y_predichos

In [18]:
cv_1layer.fit(X, Y)

Fitting 3 folds for each of 144 candidates, totalling 432 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:  2.5min
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:  9.6min
[Parallel(n_jobs=4)]: Done 432 out of 432 | elapsed: 20.8min finished


GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('scaler',
                                        MinMaxScaler(feature_range=(-1, 1))),
                                       ('nn',
                                        MLPRegressor(early_stopping=True,
                                                     max_iter=600,
                                                     random_state=42))]),
             n_jobs=4,
             param_grid={'nn__alpha': [0.0001, 0.0005, 0.001, 0.005, 0.01,
                                       0.05],
                         'nn__hidden_layer_sizes': [(50, 50), (100, 100),
                                                    (150, 150), (100, 50)],
                         'nn__learning_rate_init': [0.0001, 0.0005, 0.001,
                                                    0.005, 0.01, 0.05]},
             scoring=make_scorer(r2_score), verbose=1)

In [19]:
cv_1layer.best_score_

0.8620022959638279

In [20]:
cv_1layer.best_params_

{'nn__alpha': 0.005,
 'nn__hidden_layer_sizes': (100, 100),
 'nn__learning_rate_init': 0.01}

In [21]:
import joblib

In [22]:
joblib.dump(cv_1layer, "single_layer.model")

['single_layer.model']

Hasta aquí acaba entrenar la cinemática directa. lo que viene después es explorar los datos un poco más.

In [23]:
cv_1layer.predict(np.random.random((1,8)))

array([[ 0.03198421, -0.06785514]])

In [24]:
dataf.loc[lambda x: x["Extremo X"].le(-0.042)].sort_values("Extremo Y")

Base X    Base Y    Base Z  Extremo X  Extremo Y  Extremo Z    1    2  \
711   0.000712 -0.000290  0.000392  -0.042640  -0.024771   0.243017  800 -800   
775   0.000503 -0.000121  0.000371  -0.043598  -0.024262   0.242597  800 -800   
156   0.000510 -0.000108  0.000402  -0.043384  -0.015897   0.243406  800 -800   
826   0.000486 -0.000079  0.000435  -0.042282  -0.014457   0.244265  800 -800   
599   0.000482 -0.000092  0.000382  -0.049921  -0.011026   0.242867  800 -800   
637   0.000490 -0.000089  0.000414  -0.049627  -0.010495   0.242927  800 -800   
867   0.000554 -0.000086  0.000693  -0.042399  -0.006070   0.244479    0    0   
750   0.000572 -0.000085  0.000670  -0.043176  -0.005717   0.244211    0    0   
832   0.000674  0.000010  0.000703  -0.043431  -0.003321   0.244060    0    0   
950   0.000698  0.000012  0.000734  -0.043904  -0.002912   0.243899    0    0   
279   0.000814  0.000244  0.000730  -0.043032   0.003769   0.244453    0    0   
314   0.000806  0.000258  0.000714  -0.042085   0.005395   0.244495    0    0   
924   0.000900  0.000116  0.000756  -0.048821   0.006655   0.242853    0    0   
1095  0.000870  0.000216  0.000749  -0.049541   0.009485   0.242203    0    0   
796   0.000407 -0.000073  0.000551  -0.043848   0.012263   0.239668  800 -800   
894  -0.000148  0.000151 -0.000008  -0.044496   0.013198   0.239489  800 -800   
200  -0.000175  0.000103  0.000055  -0.044983   0.014326   0.239045  800 -800   
1002 -0.000142  0.000112 -0.000018  -0.045147   0.015401   0.238741  800 -800   
490  -0.000142  0.000117  0.000005  -0.044733   0.016687   0.238711  800 -800   
1132 -0.000154  0.000121 -0.000031  -0.044875   0.017692   0.238273  800 -800   
110  -0.000134  0.000118 -0.000004  -0.045419   0.018973   0.237514  800 -800   
234  -0.000153  0.000108 -0.000007  -0.045682   0.019928   0.237409  800 -800   
812  -0.000162  0.000106 -0.000025  -0.045797   0.023241   0.236497 -800  800   
10   -0.000162  0.000102 -0.000018  -0.045799   0.025277   0.235980 -800  800   
884  -0.000175  0.000091 -0.000022  -0.046126   0.026978   0.235577 -800  800   
518  -0.000184  0.000098 -0.000033  -0.046241   0.028575   0.235147 -800  800   
303  -0.000187  0.000096 -0.000018  -0.045969   0.030119   0.234823 -800  800   
404  -0.000197  0.000094 -0.000045  -0.046857   0.031456   0.234019 -800  800   
839  -0.000202  0.000089 -0.000016  -0.042091   0.032366   0.235207 -800  800   
674  -0.000193  0.000097 -0.000047  -0.047146   0.033239   0.233622 -800  800   
60   -0.000214  0.000094 -0.000038  -0.042118   0.033943   0.234820 -800  800   
46   -0.000192  0.000097 -0.000031  -0.047650   0.034977   0.233175 -800  800   
164  -0.000225  0.000102 -0.000060  -0.042852   0.035344   0.234199 -800  800   
889   0.000063  0.000031  0.000301  -0.043161   0.036889   0.233743 -800  800   
30    0.000046  0.000033  0.000321  -0.043890   0.038568   0.233057 -800  800   

        3    4  ...    7    8    9   10   11   12   13   14   15   16  
711     0    0  ...    0    0    0    0  800 -800  800 -800    0    0  
775     0    0  ...    0    0    0    0  800 -800  800 -800    0    0  
156     0    0  ...  800 -800  800 -800    0    0  800 -800    0    0  
826     0    0  ...  800 -800  800 -800    0    0  800 -800    0    0  
599     0    0  ...  800 -800    0    0  800 -800  800 -800    0    0  
637     0    0  ...  800 -800    0    0  800 -800  800 -800    0    0  
867   800 -800  ...    0    0    0    0  800 -800  800 -800    0    0  
750   800 -800  ...    0    0    0    0  800 -800  800 -800    0    0  
832   800 -800  ...    0    0    0    0  800 -800  800 -800    0    0  
950   800 -800  ...    0    0    0    0  800 -800  800 -800    0    0  
279   800 -800  ...  800 -800  800 -800    0    0  800 -800    0    0  
314   800 -800  ...  800 -800  800 -800    0    0  800 -800    0    0  
924   800 -800  ...  800 -800    0    0  800 -800  800 -800    0    0  
1095  800 -800  ...  800 -800    0    0  800 -800  800 -800    0    0  
796   800 -

In [25]:
dataf.iloc[939].to_numpy()[6::2]
#dataf.iloc[939].to_numpy()[6:]

array([800.,   0.,   0., 800., 800.,   0.,   0., 800.])

In [26]:
dataf.to_numpy()[6::2].max()

2300.0

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (600) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (600) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (600) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (600) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py: